sonar.projectKey=devops3rdBCA_WasteRecyclingTracker
sonar.organization=devops3rdbca
sonar.host.url=https://sonarcloud.io

# Sources
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.js,**/*.spec.jsx,**/coverage/**,build/**
sonar.coverage.exclusions=**/node_modules/**,**/*.spec.js,**/*.spec.jsx

# JavaScript/TypeScript coverage report (if you generate coverage)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Optional project metadata
sonar.projectName=Waste Recycling Tracker Frontend
sonar.projectVersion=1.0
